language: cpp
compiler: gcc
dist: bionic
notifications:
  email:
    recipients:
    - mchehab@kernel.org
    on_success: change
    on_failure: always
matrix:
  include:
  - env: TARGET_OS=bionic
  - compiler: clang
    env: TARGET_OS=bionic

before_install:
  - sudo apt-get update -qq
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu bionic main restricted universe multiverse"
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu bionic-security main restricted universe multiverse"
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu bionic-updates main restricted universe multiverse"
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu bionic-backports main restricted universe multiverse"
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y debhelper cmake pkg-kde-tools pkg-config extra-cmake-modules qtbase5-dev libqt5x11extras5-dev libkf5coreaddons-dev libkf5dbusaddons-dev libkf5i18n-dev kio-dev libkf5solid-dev libkf5widgetsaddons-dev libkf5windowsystem-dev libkf5xmlgui-dev libvlc-dev libx11-dev libxss-dev libdvbv5-dev libudev-dev

script:
  - mkdir build && cd build && cmake .. && make && sudo make install
