/* config-kaffeine.h - generated by cmake from config-kaffeine.h.cmake */

#ifndef CONFIG_KAFFEINE_H
#define CONFIG_KAFFEINE_H

#define KAFFEINE_BIN_INSTALL_DIR "${BIN_INSTALL_DIR}"
#define KAFFEINE_DATA_INSTALL_DIR "${DATA_INSTALL_DIR}"
#define KAFFEINE_LIB_INSTALL_DIR "${LIB_INSTALL_DIR}"
#define HAVE_DVB @HAVE_DVB@

#endif /* CONFIG_KAFFEINE_H */
