/* config-kaffeine.h - generated by cmake from config-kaffeine.h.cmake */

#ifndef CONFIG_KAFFEINE_H
#define CONFIG_KAFFEINE_H

#define KAFFEINE_DATA_INSTALL_DIR "${DATA_INSTALL_DIR}"
#define KAFFEINE_PLUGIN_INSTALL_DIR "${PLUGIN_INSTALL_DIR}"

#endif /* CONFIG_KAFFEINE_H */
