name: CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  Ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    container:
      image: ubuntu:26.04
    strategy:
      matrix:
        arch: [x64_64, aarch64]
    steps:
      - uses: actions/checkout@v2
      - name: prepare
        run: |
          apt-get update
          apt-get install -y cmake extra-cmake-modules make g++ \
           gettext libvlc-dev pkg-config libdvbv5-dev \
           qt6-base-dev qt6-base-dev-tools qt6-declarative-dev \
           qt6-tools-dev-tools libkf6i18n-dev libkf6widgetsaddons-dev \
           libkf6xmlgui-dev libkf6coreaddons-dev libkf6windowsystem-dev \
           libkf6kio-dev libkf6solid-dev libkf6dbusaddons-dev \
           libvulkan-dev libfreetype-dev libfontconfig1-dev
      - name: build
        run: |
          cmake .
          make
          sudo make install
